### ISSUE TITLE
found dead link

### ISSUE THREAD

**Issue by txt-file** [learn-chef/course-Manage-Your-Fleet-with-Chef-Infra#2]
## :ghost: Brief Description

I found a dead link.

## Steps To Reproduce

1. Go to course `Infra101` -> `Expand your Chef Infra language skills` -> `Learn more about Policyfiles` -> `Collect the Infra code`
2. Click on the link "[this blog post.](https://blog.chef.io/2017/02/14/writing-wrapper-cookbooks/)" in the infobox
3. get https://www.chef.io/blog front page

## :police_car: Expected behavior

I expect a blog post instead of the blogs front page.

## :heavy_plus_sign: Additional context

currently working link is https://www.chef.io/blog/writing-wrapper-cookbooks

**Comment by damacus** [comment]
Thanks for reporting this, this is now fixed 🚀
